;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="CutterType",DevComment="")
+GameplayTagList=(Tag="CutterType.Auto",DevComment="変形後勝手に動作するカッター")
+GameplayTagList=(Tag="CutterType.Auto.Expand",DevComment="")
+GameplayTagList=(Tag="CutterType.Controll",DevComment="プレイヤーが生成、操作できるカッター")
+GameplayTagList=(Tag="CutterType.Controll.Circle",DevComment="")
+GameplayTagList=(Tag="CutterType.Controll.Straight",DevComment="")

