;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="CutterType.Controll.Circlr",NewTagName="CutterType.Controll.Circle")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="CannonType",DevComment="")
+GameplayTagList=(Tag="CutterType",DevComment="")
+GameplayTagList=(Tag="CutterType.Auto",DevComment="変形後自動で移動するCutter")
+GameplayTagList=(Tag="CutterType.Auto.Expand",DevComment="")
+GameplayTagList=(Tag="CutterType.Controll",DevComment="プレイヤーが生成、動作させられるCutter")
+GameplayTagList=(Tag="CutterType.Controll.Circle",DevComment="")
+GameplayTagList=(Tag="CutterType.Controll.FractalCircle",DevComment="")
+GameplayTagList=(Tag="CutterType.Controll.StraightYoYo",DevComment="")

